#!/bin/bash
echo -e "[RUBOCOP] --> Init (wait a second)"

FAILS=`bundle exec rubocop | grep 'no offenses detected' -o | awk '{print $1}'`

if [ "$FAILS" == "no" ]; then
  echo -e "[RUBOCOP] --> 👍 approved."
  exit 0
else
  echo -e "[RUBOCOP] --> ✋  You have offenses!!!"
  exit 1
fi
